services:
  web:
    build:
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    deploy:
      resources:
        limits:
          memory: 512M
